### ISSUE TITLE
Memoized values - am I doing this correctly?

### ISSUE THREAD

**Issue by richardgorman** [react-spring/zustand#106]
I'm trying to create an optimised selector. The selector is shared amongst several components so it accepts a parameter from outside:

```js
const defaultValue = {};

const useSingleValue = id => useStore(
  useCallback(state => state[id] || defaultValue, [id])
);
```

Is this the correct way to go about it?

**Comment by drcmda** [comment]
thats quite clever, maybe too clever. ;-) but really i wouldn't worry about selectors. it's nothing at all, no expense, maybe we should even remove the entry in the github docs.

**Comment by richardgorman** [comment]
It's true that this is a really simple example. If the selector actually computed something complex, would this be the correct approach?

**Comment by mongris** [comment]
I have similar situation like a more complex implement, is it correct approach?

```js
const { list, loading, actions } = useStore(
  state => {
    if (!byPlayer) {
      return {
        list: state.transactions,
        loading: state.loading,
        actions: state.actions
      }
    }
    return {
      list: state.transactionsByPlayer.data[byPlayer] || { total: 0 },
      loading: state.loading,
      actions: state.actions
    }
  },
  shadowEuqlityChecker
)
```

**Comment by dai-shi** [comment]
Basically, selectors should be lightweight as much as possible.
If you need heavy computation, please consider using `useMemo`.
```js
const value = useStore(...);
const computedValue = useMemo(() => ..., [value]);
```

Closing this. Feel free to reopen for further discussion.

**Comment by HarrisonB** [comment]
Seems like the docs were changed to encourage usage of `useCallback`? What changed?

**Comment by dai-shi** [comment]
@HarrisonB Are you referring to this note? https://github.com/react-spring/zustand#memoizing-selectors

Stable selectors (either with useCallback, or defining outside) will allow skipping unnecessary computation, which could improve performance.

**Comment by HarrisonB** [comment]
@dai-shi, right, but then @drcmda is saying the opposite in this comment: https://github.com/react-spring/zustand/issues/106#issuecomment-617855715

**Comment by dai-shi** [comment]
Long story short, we discussed and changed our recommendation.
The main reason is we plan to use `useMutableSource` in v4, and it recommends stable selectors for optimization. So, we recommend it in v3 too, to prepare for v4.

v3 (as well as v2) optimizes with stable selectors too to some extent. It's trivial if the selectors are lightweight. Unnecessary computation is just about calling the selectors. If a selector is not referentially changed and the state is not changed, we skip calling the selector. It has nothing to do with re-renders. If a selector is very lightweight (ex. `state => state.foo`) skipping it is almost nothing. btw, useCallback is not zero cost, so in total we don't know which is better. The best is define the selector outside render, so we don't even need useCallback (if the selector doesn't depend on other values.)

**Comment by HarrisonB** [comment]
Gotcha. Thanks for the thorough explanation!

**Comment by alexanderchan** [comment]
Just thinking out loud here, I've been toying with the idea of proxies in environments that support it for simple state selectors, it'd be nice to possibly get it to work for nested selectors as well.  Maybe it's one way to prevent having to duplicate a set of selectors that mirrors the state object?

```
const memoizedSelectors = {};
const selector = new Proxy(memoizedSelectors, {
  get: function (target: any, prop: string) {
    // if the selector is not found, we create a new one
    // and cache the selector
    if (target[prop] === undefined) {
      target[prop] = (state: any) => state?.[prop];
    }
    return target[prop];
  },
});

// Then, instead of
// const berriesSelector = state => state.berries
// function Component() {
// // const berries = useStore(berriesSelector)
// const berries = useStore(selector.berries)
// ...
// }
```

we could use a `WeakMap`  to possibly allow for garbage collection but that seems like overkill since there really shouldn't be that many selectors.

However, if we're going to go down the proxies route, I would bet that we wouldn't even need selectors because 

```
const { value } = selector
```

also triggers the proxy to be called and if we could register the component as a listener.  Then it gets close to what mobx is doing but without having to wrap everything in an `observer`.

**Comment by dai-shi** [comment]
Hi, nice try and thinking out loud.

> ```
> const berries = useStore(selector.berries)
> ```

If I were to support getting just a property (non-nested), I'd use a custom hook.

```js
const useStoreProp = (prop) => {
  const selector = useCallback((state) => state[prop], [prop])
  return useStore(selector)
}
```

> ```
> const { value } = selector
> ```

Good point. It's almost what [react-tracked](https://github.com/dai-shi/react-tracked) does.

**Comment by alexanderchan** [comment]
@dai-shi thanks that's a good idea, I might give the hook version a try next time -- we could always use something like a lodash or other [just safe get](https://github.com/angus-c/just/tree/master/packages/object-safe-get) to support a string version of the nested prop pretty easily so that should cover a lot of the cases.

Thanks the pointer to react-tracked I'll check it out.  It's hard to keep "track" of all of the nice state libraries you've got on the go!  Also thanks for sharing things like zustand and jotai as well 👍

**Comment by ethanneff** [comment]
> please consider using useMemo.

`useMemo` cannot be used outside a component. This is not an app-wide caching solution.
