### ISSUE TITLE
get() is undefined during store creation

### ISSUE THREAD

**Issue by IljaDaderko** [react-spring/zustand#116]
I've got a simple store I added below. Idea here is to have platform and action that gets it. I also added computed / helper booleans like `isAndroid`. For some reason whenever I use one of these booleans I see an error `can not get platform of undefined`. This is fixed by changing those helper booleans to `get().platform`. But I don't understand why get is undefined. Should it not already include an initial store?  Perhaps it is only undefined when store is being created?

```ts
import create from 'zustand';

interface PlatformStore {
  platform: 'web' | 'ios' | 'android' | 'electron';
  isAndroid: boolean;
  isIos: boolean;
  isWeb: boolean;
  getPlatform: () => Promise<void>;
}

const [usePlatformStore] = create<PlatformStore>((set, get) => ({
  platform: 'web',

  isAndroid: get().platform === 'android',

  isIos: get().platform === 'ios',

  isWeb: get().platform === 'web',

  async getPlatform() { /* gets platform and uses set() to add it to the store */ }
));
```

**Comment by cosmophile** [comment]
The function passed to `create` is what returns the initial state, which is obviously undefined before it is created. Eg: isAndroid is a literal property you are creating within the initial state so it cannot have access to the as yet-uncreated state. 

You can change that property to a function that will be run at access time, and then it would work because it closes over `get` at creation time:

```isAndroid: () => get().platform === 'web' ```

(which is same as `api.getState().platform === 'web'`)

FWIW, as I've used zustand more and more I have moved towards only using actual state - which I can subscribe to with hooks - in my initial state, and using api getters and setters for all the rest. That way I can look at the create function's object and know my exact state shape without being bogged down by setters and getters. So I'd write your state like:

``` 
const [useStore, api] = create(() => ({platform: 'web'}))
export const usePlatform = () => useStore(store => store.platform) // utility function to subscribe to platform changes, you can obviously keep using useStore directly too.
export const setPlatform = platform => api.setState({platform})
export const isAndroid = () => api.getState().platform === 'android'
//...etc
```

Not saying the above is the best way, just wanted to demonstrate that you can create any helper functions you like outside the create function too, and export them as and where you need.

**Comment by IljaDaderko** [comment]
This was it. Thank you for the explanation. And yeh I considered approach you mentioned, but in my case it becomes very repetitive, so I wanted to store these values in the state as some sort of `computed` flags I can access.
