### ISSUE TITLE
Does not trigger rerender

### ISSUE THREAD

**Issue by dy** [react-spring/zustand#15]
I intended to use zustand as singleton hook for history, as so:

```js
import { createBrowserHistory } from 'history'
import delegate from 'delegate-it'
import create from 'zustand'

// global-ish history tracker
export const [ useHistory ] = create(set => {
  let history = createBrowserHistory()

  const unlisten = history.listen((location, action) => {
    // NOTE: passing history object as-is does not trigger rerendering
    set(history)
  })

  let delegation = delegate('a', 'click', e => {
    e.preventDefault()
    history.push(e.delegateTarget.getAttribute('href'))
  });
  return history
})
```
The problem is that passing unchanged state object to `set` does not trigger rerendering, as noted in the commentary. For that purpose we have to create a clone as
```js
set({...history})
```
Is that planned behavior? That isn't what expected.
Thanks

**Comment by drcmda** [comment]
It’s using reference equality for change detection. Setting the same object won’t cause Rezensentin, similar to how Redux reduces state.

**Comment by dy** [comment]
The problem persists is even if passing clone of the object
```js
// global-ish history tracker
export const [ useHistory ] = create(set => {
  let history = createBrowserHistory()

  const unlisten = history.listen((location, action) => {
    set({...history})
  })

  let delegation = delegate('a', 'click', e => {
    e.preventDefault()
    history.push(e.delegateTarget.getAttribute('href'))
  });
  return {...history}
})
```

**Comment by JeremyRH** [comment]
It isn't updating because all the enumerable properties on `history` are the same. The check to update state is a "shallow equal" check. It will first check if the value is equal and if not, check all enumerable properties for equality. Even though you created a new history object, the enumerable properties were the same so it did not set the state.

It looks like you are trying to call `set` when the history event is dispatched. You should create your own state with `{ location }` and set the location value in the listener. If you need access to the history object outside of the store, create it outside of the store in a module and import it whenever you need it.
