### ISSUE TITLE
Unable to reset/replace state

### ISSUE THREAD

**Issue by laurib** [react-spring/zustand#74]
Using immer and redux middlewares. 

i want to replace initial state with new state, but as zustand merges with ``set``, then it is quite impossible. 

```
defaultState  = {
  isLoading: false,
}
```

replace state with redux middleware:
From immer doc:
```
case "loadUsers":
            // OK: we return an entirely new state
            return action.payload
```

This should replace state entirely but ``isLoading`` is still present. How to replace entire state ?

or if i ``return {}`` then all old values are still in place

Tried different ways. immer middleware / using immer in redux middleware for set / added immer to reducer.. But was still unable to do it

**Comment by JeremyRH** [comment]
@laurib Unfortunately, Zustand's `set` doesn't allow this right now. I guess the best option is to store all your state in a property and overwrite that property. That's kind of messy but I think a `create` wrapper can abstract this for you:
```js
import create from "zustand";

function createNoMerge(stateCreator) {
  let setState;
  let getState;

  const [useStore, api] = create((set, get) => {
    setState = newState => {
      const oldState = get().state;
      const state =
        typeof newState === "function"
          ? newState(oldState)
          : newState;
      return set({ state });
    };
    getState = () => get().state;
    return {
      state: stateCreator(setState, getState)
    };
  });

  api.setState = setState;
  api.getState = getState;

  const useStoreNoMerge = (sel = s => s, ...args) => {
    const selector = () => sel(getState());
    return useStore(selector, ...args);
  };

  return [useStoreNoMerge, api];
}

const [useStore, api] = createNoMerge(() => ({
  a: 1,
  b: 2
}));
```

**Comment by MrFungusEli** [comment]
Are there any plans to change `set` to support this?
Thanks in advance!

**Comment by JeremyRH** [comment]
@MrFungusEli I would like the default behavior of `set` to overwrite instead of merge. That would be a breaking change though.

**Comment by drcmda** [comment]
wouldnt overwrite require full reducers though? like when you just want to change a single value.

**Comment by MrFungusEli** [comment]
Is there anything I can do to help? I'm wondering if this would be a good first time contribution for me :)

**Comment by drcmda** [comment]
i guess making it merge or not is a small change, but the repercussions of how it effects all purposes and use cases isn't clear to me. from my experience, resetting a set of objects is rare, i solve it via intialState. plain deletion i haven't ran into. merging, or set(value) instead of set(function) on the other hand is something i do often - i realize this could just be me.

if the change would make set(value) obsolete because it would now delete all data except the one prop that it gets, and set(function) would always have to spread, then i think it needs a bigger discussion involving more users. we should also look into what made react go for setState and useState as a merging op.

**Comment by MrFungusEli** [comment]
> you should be able to set the initialState variable
> 
> ```js-jsx
> const initialState = { ... }
> const [useStore, api] = create(set => initialState)
> api.setState(initialState)
> ```

I must have missed this, this works absolutely fine for me. Thanks!
